### PR TITLE
Fix compilation errors

### LINKED ISSUE #473: Errors compiling bito with GitHub action and locally
The `build-with-cmake` action currently fails. I get the same errors on my laptop.
Errors are coming from warnings updated to errors due to `-DWERROR=OFF`.

### PR DESCRIPTION
**Pull request by 4ment**
## Fix compilation errors

Small changes:
- iterate elements in a for loop by reference
- remove useless loop

Bigger change:
The `doctest.h` file is updated using the latest version (v2.4.11) since this error was generated:
```
/home/runner/work/bito/bito/src/doctest.h:4140:47: error: size of array ‘altStackMem’ is not an integral constant-expression
 4140 |         static char             altStackMem[4 * SIGSTKSZ];
```

Maybe doctest could be a submodule?

Closes #473 

## Tests

The `build-with-cmake` Github action runs without any error. It also builds locally with docker.

## Checklist:

* [ ] Code follows our detailed [contribution guidelines](CONTRIBUTING.md)
* [ ] `clang-format` has been run
* [ ] TODOs have been eliminated from the code
* [ ] Comments are up to date, document intent, and there are no commented-out code blocks
* [ ] Issue branch has been squashed and rebased on main branch
* [ ] GitHub CI build on PR branch completed successfully

### CODE REVIEW

**Comment by matsen** [comment]
@davidrich27 can you have a look? Also, I know you were doing some refactoring of unit tests...

**Comment by 4ment** [comment]
I enabled GitHub actions on a separate branch when I was debugging. You can see the errors [here](https://github.com/4ment/bito/actions)

**Comment by davidrich27** [comment]
Yes I will check this out.

**Review by matsen — APPROVED** [review]
Works great on my side. Thanks @4ment !

**Pull request merged**
