### PR TITLE
Github Action: Run Tests fixes.

### LINKED ISSUE #419: Solve issues with Github Action CI
Github Action CI `Run test` still fails on run.  Passes on Quokka and macOS environments.

### PR DESCRIPTION
**Pull request by davidrich27**
## Description

This fixes the Github Action `Run Tests`.  

*  Selects a version of GCC (uses ver. 7.XX)
*  Symlinks PyTest installed via Apt.

Closes #419 

## Tests

N/A

## Checklist:

* [x] Code follows our detailed [contribution guidelines](CONTRIBUTING.md)
* [x] `clang-format` has been run
* [x] TODOs have been eliminated from the code
* [x] Comments are up to date, document intent, and there are no commented-out code blocks
* [ ] GitHub CI build on PR branch completed successfully

### CODE REVIEW

**Comment by davidrich27** [comment]
This is intended as a stopgap, so we have a CI that runs doctest and pytest successfully.  Our tests will eventually need to run correctly on the latest compiler, but for now this runs the CI tests on gcc 7.XX.

**Comment by ognian-** [comment]
Looks good! Is there a chance the GCC from "setup-gcc" be replaced in the next step by "apt install build-essential"?

**Comment by davidrich27** [comment]
Yes.  I was trying to get access to an older version of gcc/g++.  The only version of build-essential my local machine showed was v12.  Now instead of the separate action, it just installs through apt and set an environmental variable.   Is this what you were thinking?

**Comment by ognian-** [comment]
I was worried whether apt install would override the previously installed gcc by setup-gcc. Both versions will be available, but I wasn't sure which one would be the default.

**Review by matsen — APPROVED** [review]

**Pull request merged**
